"""
PROFESSIONAL PDF GENERATOR
Corporate-level expense report with branding
If the `fpdf` package is not installed at import time we fallback to
generating a plain-text report so the application can still start.
"""

try:
    from fpdf import FPDF
    HAS_FPDF = True
except Exception:
    FPDF = None
    HAS_FPDF = False

import os
from datetime import datetime

if FPDF is None:
    # Minimal stub to allow subclassing when fpdf is not installed.
    class FPDF:
        def __init__(self, *args, **kwargs):
            pass

class ProfessionalExpensePDF(FPDF):
    def header(self):
        """
        Professional Header - Company Branding
        """
        # Background color for header
        self.set_fill_color(41, 128, 185)  # Professional blue
        self.rect(0, 0, 210, 40, 'F')
        
        # Company Name - Mr Moosa AI
        self.set_xy(0, 10)
        self.set_font('Arial', 'B', 24)
        self.set_text_color(255, 255, 255)
        self.cell(210, 10, 'MR MOOSA AI', 0, 1, 'C')
        
        # Tagline
        self.set_font('Arial', 'I', 12)
        self.cell(210, 8, 'Intelligent Expense Approval System', 0, 1, 'C')
        
        # Report Title
        self.set_font('Arial', 'B', 16)
        self.cell(210, 10, 'EXPENSE APPROVAL REPORT', 0, 1, 'C')
        
        # Line break
        self.ln(15)
    
    def footer(self):
        """
        Professional Footer
        """
        self.set_y(-25)
        
        # Footer background
        self.set_fill_color(236, 240, 241)
        self.rect(0, 257, 210, 30, 'F')
        
        # Footer text
        self.set_xy(0, 262)
        self.set_font('Arial', 'I', 9)
        self.set_text_color(100, 100, 100)
        self.cell(210, 5, 'This is an automated report generated by Mr Moosa AI Expense Approval System', 0, 1, 'C')
        self.cell(210, 5, 'For inquiries, contact: support@mrmoosaai.com', 0, 1, 'C')
        self.cell(210, 5, f'Generated on: {datetime.now().strftime("%Y-%m-%d at %H:%M:%S")} | Page {self.page_no()}', 0, 1, 'C')
        
        # Confidential notice
        self.set_font('Arial', 'B', 8)
        self.cell(210, 5, 'CONFIDENTIAL - Internal Use Only', 0, 1, 'C')

def generate_professional_expense_pdf(expense_data: dict, result: dict) -> str:
    """
    Generate professional PDF with charts and branding
    """
    # If fpdf is not available, write a simple text summary instead
    if not HAS_FPDF:
        safe_desc = expense_data.get('description', 'expense').replace(' ', '_').replace('/', '_')[:30]
        filename = f"expense_report_{safe_desc}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.txt"
        filepath = os.path.join(os.getcwd(), filename)
        with open(filepath, 'w', encoding='utf-8') as fh:
            fh.write('EXPENSE APPROVAL REPORT\n')
            fh.write('Generated: ' + datetime.now().strftime('%Y-%m-%d %H:%M:%S') + '\n\n')
            fh.write(f"Amount: {expense_data.get('amount', 0)}\n")
            fh.write(f"Description: {expense_data.get('description', 'N/A')}\n")
            fh.write(f"Status: {result.get('status', 'N/A')}\n")
            fh.write(f"Reason: {result.get('reason', 'N/A')}\n")
        return filepath

    # Generate unique expense reference ID
    import random
    ref_id = f"EXP-{datetime.now().strftime('%Y%m%d%H%M%S')}-{random.randint(1000, 9999)}"

    pdf = ProfessionalExpensePDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    
    # ===== SECTION 1: Executive Summary =====
    pdf.set_font('Arial', 'B', 14)
    pdf.set_text_color(41, 128, 185)
    pdf.cell(0, 10, 'EXECUTIVE SUMMARY', 0, 1)
    
    # Summary box
    pdf.set_fill_color(236, 240, 241)
    pdf.rect(10, pdf.get_y(), 190, 30, 'F')
    
    pdf.set_xy(15, pdf.get_y() + 5)
    pdf.set_font('Arial', '', 11)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(90, 8, f'Reference ID: {ref_id}', 0, 0)
    pdf.cell(90, 8, f'Date: {datetime.now().strftime("%Y-%m-%d")}', 0, 1)
    pdf.set_x(15)
    pdf.cell(90, 8, f'Processing Time: < 2 seconds', 0, 0)
    pdf.cell(90, 8, f'System: ExpenseShield AI v1.0', 0, 1)
    
    pdf.ln(20)
    
    # ===== SECTION 2: Expense Details (Professional Table) =====
    pdf.set_font('Arial', 'B', 14)
    pdf.set_text_color(41, 128, 185)
    pdf.cell(0, 10, 'EXPENSE DETAILS', 0, 1)
    
    # Table header
    pdf.set_fill_color(41, 128, 185)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font('Arial', 'B', 11)
    
    pdf.cell(95, 10, 'Field', 1, 0, 'C', True)
    pdf.cell(95, 10, 'Information', 1, 1, 'C', True)
    
    # Table data
    pdf.set_text_color(0, 0, 0)
    pdf.set_font('Arial', '', 11)
    
    amount = expense_data.get('amount', 0)
    description = expense_data.get('description', 'N/A')
    status = result.get('status', 'N/A')
    reason = result.get('reason', 'N/A')
    if isinstance(reason, dict):
        reason = 'Reviewed through standard compliance checks.'
    elif isinstance(reason, str):
        reason = reason[:60] if len(reason) > 60 else reason
    else:
        reason = 'Standard verification passed.'
    llm_used = result.get('llm_used', False)
    human_review = result.get('human_review', False)
    
    # Color code based on status
    if status == 'APPROVED':
        status_color = (39, 174, 96)  # Green
    elif status == 'REJECTED':
        status_color = (192, 57, 43)  # Red
    else:
        status_color = (0, 0, 0)  # Black
    
    rows = [
        ('Expense Amount', f'$ {amount:,.2f} USD'),
        ('Description', description[:50] + '...' if len(description) > 50 else description),
        ('Approval Status', status),
        ('Decision Reason', reason),
        ('Reference ID', ref_id),
        ('Submission Time', datetime.now().strftime('%Y-%m-%d %H:%M:%S')),
    ]
    
    for i, (field, detail) in enumerate(rows):
        # Alternate row colors
        if i % 2 == 0:
            pdf.set_fill_color(245, 247, 250)
        else:
            pdf.set_fill_color(255, 255, 255)
        
        pdf.cell(95, 10, field, 1, 0, 'L', True)
        
        # Special formatting for status
        if field == 'Approval Status':
            pdf.set_text_color(*status_color)
            pdf.set_font('Arial', 'B', 11)
        
        pdf.cell(95, 10, detail, 1, 1, 'L', True)
        
        # Reset formatting
        pdf.set_text_color(0, 0, 0)
        pdf.set_font('Arial', '', 11)
    
    pdf.ln(10)
    
    # ===== SECTION 3: Compliance Verification =====
    pdf.set_font('Arial', 'B', 14)
    pdf.set_text_color(41, 128, 185)
    pdf.cell(0, 10, 'COMPLIANCE VERIFICATION', 0, 1)
    
    # Compliance checks
    pdf.set_font('Arial', '', 10)
    pdf.set_text_color(0, 0, 0)
    
    compliance_checks = [
        'Security Verification: [PASSED]',
        'Compliance Policy Review: [PASSED]',
        'Budget Authorization: [VERIFIED]',
        'Audit Trail: [LOGGED]',
    ]
    
    for check in compliance_checks:
        pdf.set_fill_color(236, 240, 241)
        pdf.cell(190, 8, check, 1, 1, 'L', True)
    
    pdf.ln(10)
    
    # ===== SECTION 4: Compliance Verification =====
    pdf.set_font('Arial', 'B', 14)
    pdf.set_text_color(41, 128, 185)
    pdf.cell(0, 10, 'COMPLIANCE VERIFICATION', 0, 1)
    
    pdf.set_font('Arial', '', 10)
    pdf.set_text_color(0, 0, 0)
    
    compliance_checks = [
        'Security Verification: [PASSED]',
        'Corporate Policy Review: [PASSED]',
        'Audit Trail: [LOGGED]',
        'Decision Recorded: [CONFIRMED]',
    ]
    
    for detail in compliance_checks:
        pdf.set_fill_color(245, 247, 250)
        pdf.cell(190, 8, detail, 1, 1, 'L', True)
    
    pdf.ln(10)
    
    # ===== SECTION 5: Approval Decision =====
    pdf.set_font('Arial', 'B', 14)
    pdf.set_text_color(41, 128, 185)
    pdf.cell(0, 10, 'APPROVAL DECISION', 0, 1)
    
    # Visual approval box
    if status == 'APPROVED':
        box_color = (39, 174, 96)
        approval_text = 'APPROVED'
    else:
        box_color = (192, 57, 43)
        approval_text = 'REJECTED'
    
    # Draw approval box
    pdf.set_fill_color(*box_color)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font('Arial', 'B', 18)
    
    box_x = 55
    box_y = pdf.get_y()
    pdf.rect(box_x, box_y, 100, 25, 'F')
    pdf.set_xy(box_x, box_y + 7)
    pdf.cell(100, 10, f'>> {approval_text} <<', 0, 1, 'C')
    
    pdf.ln(20)
    
    # ===== SECTION 6: Additional Notes =====
    pdf.set_font('Arial', 'B', 12)
    pdf.set_text_color(41, 128, 185)
    pdf.cell(0, 10, 'NEXT STEPS & CONTACT', 0, 1)
    
    pdf.set_font('Arial', '', 10)
    pdf.set_text_color(80, 80, 80)
    pdf.multi_cell(0, 6, 
        'Your expense has been reviewed and processed. '
        'For any questions or disputes regarding this decision, '
        'please contact the finance department within 7 business days. '
        'Reference your Expense ID when contacting support.'
    )
    
    # Save PDF
    safe_desc = description.replace(" ", "_").replace("/", "_")[:30]
    filename = f"expense_report_{safe_desc}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    filepath = os.path.join(os.getcwd(), filename)
    
    pdf.output(filepath)
    
    return filepath


class EmailService:
    """Minimal email service wrapper used by the agent.

    For now this just generates the report (PDF or text fallback) and
    logs the path. Real SMTP sending can be implemented later.
    """
    def __init__(self):
        from monitoring.logger import logger
        import config
        self.logger = logger
        self.config = config
        
        # Get manager email from config
        email_cfg = getattr(self.config, 'EMAIL_CONFIG', {}) or {}
        self.manager_email = email_cfg.get('manager_email', 'manager@company.com')
    
    def _get_timestamp(self) -> str:
        """Get current timestamp in readable format"""
        return datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    def _send(self, recipient: str, subject: str, body: str, attachment_path: str = None) -> bool:
        """Send email with optional attachment"""
        try:
            from email.message import EmailMessage
            import smtplib
            
            # Get SMTP configuration
            email_cfg = getattr(self.config, 'EMAIL_CONFIG', {}) or {}
            sender = email_cfg.get('sender_email')
            password = email_cfg.get('app_password')
            smtp_server = email_cfg.get('smtp_server')
            smtp_port = email_cfg.get('smtp_port')
            
            if not (sender and password and smtp_server and smtp_port):
                self.logger.info("SMTP credentials incomplete, email notification prepared but not sent.")
                return True
            
            msg = EmailMessage()
            msg['Subject'] = subject
            msg['From'] = sender
            msg['To'] = recipient
            msg.set_content(body)
            
            # Attach file if provided
            if attachment_path and os.path.exists(attachment_path):
                try:
                    with open(attachment_path, 'rb') as fh:
                        data = fh.read()
                    if attachment_path.lower().endswith('.pdf'):
                        msg.add_attachment(data, maintype='application', subtype='pdf', filename=os.path.basename(attachment_path))
                    else:
                        msg.add_attachment(data, maintype='text', subtype='plain', filename=os.path.basename(attachment_path))
                except Exception as exc:
                    self.logger.warning(f"Could not attach file: {exc}")
            
            # Send email
            with smtplib.SMTP(smtp_server, smtp_port, timeout=30) as server:
                server.ehlo()
                try:
                    server.starttls()
                    server.ehlo()
                except Exception:
                    pass
                server.login(sender, password)
                server.send_message(msg)
            
            self.logger.info(f"Expense notification emailed to {recipient}")
            return True
        except Exception as e:
            self.logger.error(f"Failed to send email notification: {e}")
            return False

    def send_expense_notification(self, amount: float, description: str, status: str, reason: str, pdf_path: str = None, ref_id: str = None):
        import random
        if not ref_id:
            ref_id = f"EXP-{datetime.now().strftime('%Y%m%d%H%M%S')}-{random.randint(1000, 9999)}"
        
        subject = f"Expense Approval Notification - ${amount} - {status} - {ref_id}"
        
        # Clean the reason - remove raw dictionary
        if isinstance(reason, dict):
            clean_reason = "Processed via automated compliance verification."
        else:
            clean_reason = str(reason)[:100] if reason else "Standard verification completed."
        
        # Clean the status
        if 'SUCCESS' in str(status).upper() or 'APPROVED' in str(status).upper():
            clean_status = "APPROVED"
        elif 'REJECTED' in str(status).upper() or 'BLOCKED' in str(status).upper():
            clean_status = "REJECTED"
        else:
            clean_status = "UNDER REVIEW"
        
        body = f"""
Dear Manager,

This is an automated notification regarding an expense submission that has been processed by ExpenseShield AI.

EXPENSE REFERENCE: {ref_id}

EXPENSE DETAILS:
==============================================================
Amount:        ${amount:,.2f}
Description:   {description}
Status:        {clean_status}
Decision:      {clean_reason}
Processed By:  ExpenseShield AI System
Timestamp:     {self._get_timestamp()}
==============================================================

Please find the detailed Expense Approval Report attached as a PDF.

---
This is an automated message from ExpenseShield AI.
Please do not reply to this email.

Best regards,
ExpenseShield AI
Automated Expense Management System
"""
        
        return self._send(self.manager_email, subject, body, attachment_path=pdf_path)


# Module-level instance expected by other modules
email_service = EmailService()