#!/usr/bin/env bash
# Quick Start Guide for Audit Logging System
# Audit logging system کو start کرنے کے لیے quick commands

echo "════════════════════════════════════════════════════════"
echo "🔐 AUDIT LOGGING SYSTEM - QUICK START GUIDE"
echo "════════════════════════════════════════════════════════"
echo ""

echo "✅ SYSTEM STATUS:"
echo "   • Audit logging: ✓ INTEGRATED"
echo "   • Tamper protection: ✓ ENABLED (HMAC-SHA256)"
echo "   • CSV location: audit_logs/decisions.csv"
echo "   • CLI utility: audit_cli.py"
echo ""

echo "🚀 QUICK COMMANDS:"
echo ""
echo "1. View audit logs:"
echo "   python audit_cli.py logs --limit 20"
echo ""
echo "2. Show statistics:"
echo "   python audit_cli.py stats"
echo ""
echo "3. Verify integrity (check for tampering):"
echo "   python audit_cli.py verify"
echo ""
echo "4. Export comprehensive report:"
echo "   python audit_cli.py export"
echo ""
echo "5. Find specific expense:"
echo "   python audit_cli.py find EXP001"
echo ""
echo "6. Count records by agent:"
echo "   python audit_cli.py count --agent 'Finance Agent'"
echo ""
echo "7. Run full test suite:"
echo "   python test_audit_logging.py"
echo ""
echo "8. Quick summary:"
echo "   python audit_cli.py summary"
echo ""

echo "📋 IN YOUR PYTHON CODE:"
echo ""
echo "from monitoring.audit_logger import audit_logger"
echo "from monitoring.audit_viewer import audit_viewer"
echo ""
echo "# Automatically logs when agents process expenses"
echo "result = await agent_system.process({...})"
echo ""
echo "# Manual audit operations:"
echo "audit_logger.log_decision(...)"
echo "audit_viewer.display_logs()"
echo "audit_viewer.verify_and_report()"
echo "audit_viewer.export_detailed_report()"
echo ""

echo "🔐 SECURITY FEATURES:"
echo "   ✅ HMAC-SHA256 signing on every record"
echo "   ✅ Tamper detection with hash mismatch alerts"
echo "   ✅ Transaction IDs for correlation"
echo "   ✅ JSON export with full audit trail"
echo ""

echo "📊 AUDIT LOG FORMAT:"
echo "   • timestamp: When decision was made"
echo "   • agent_name: Which agent made decision"
echo "   • expense_id: Expense identifier"
echo "   • decision: APPROVED/BLOCKED/REQUIRES_APPROVAL"
echo "   • hash: HMAC-SHA256 signature (tampering detection)"
echo ""

echo "⚙️ INTEGRATION POINTS:"
echo "   • SecurityAgent → Logs security decisions"
echo "   • FinanceAgent → Logs budget approvals"
echo "   • SkillAgent → Logs skill execution"
echo "   • OrchestratorAgent → Logs final decisions"
echo ""

echo "════════════════════════════════════════════════════════"
echo "📖 For detailed documentation: AUDIT_LOGGING_GUIDE.md"
echo "════════════════════════════════════════════════════════"
